In [4]:
4+5


9

In [1]:
!pip install numpy 

'pip' is not recognized as an internal or external command,
operable program or batch file.


In [5]:
import numpy as np

In [6]:
a= np.array([5,7,8])
a

array([5, 7, 8])

In [8]:
a.shape    #tells dimension

(3,)

In [7]:
b = np.array([[5,7,8], [7,3,4]])
b

array([[5, 7, 8],
       [7, 3, 4]])

In [9]:
# 3d matrix
d=np.array([[[4,8,7],[3,1,5],[6,9,13]],[[41,81,71],[31,11,51],[61,91,131]]])
d

array([[[  4,   8,   7],
        [  3,   1,   5],
        [  6,   9,  13]],

       [[ 41,  81,  71],
        [ 31,  11,  51],
        [ 61,  91, 131]]])

In [10]:
d.shape

(2, 3, 3)

In [14]:

c = np.array([[3,8,4], [9,3,5],[11,15,17],[19,31,8]])
c

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [15]:
c[1,0]

9

In [16]:
d[1,0,2]

71

In [19]:
c[0:4:1,2]

array([ 4,  5, 17,  8])

In [21]:
c[:,1:2]

array([[ 8],
       [ 3],
       [15],
       [31]])

In [22]:
d[:2,-2:,:1]

array([[[ 3],
        [ 6]],

       [[31],
        [61]]])

In [25]:
m = np.array([
    [[4,41], [8,81], [7,71]],
    [[3,31], [1,11], [5,51]],
    [[6,91], [9,91], [13,131]]
    ])
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  91],
        [  9,  91],
        [ 13, 131]]])

In [27]:
m.shape

(3, 3, 2)

In [23]:
d[-1:,-2:,:]

array([[[ 31,  11,  51],
        [ 61,  91, 131]]])

In [28]:
c[0,0] =505
c

array([[505,   8,   4],
       [  9,   3,   5],
       [ 11,  15,  17],
       [ 19,  31,   8]])

In [29]:
c[1,:]=([4,5,6])
c

array([[505,   8,   4],
       [  4,   5,   6],
       [ 11,  15,  17],
       [ 19,  31,   8]])

In [32]:
c[:,1]=[65,7,8,2]
c

array([[505,  65,   4],
       [  4,   7,   6],
       [ 11,   8,  17],
       [ 19,   2,   8]])

In [34]:
c+3

array([[508,  68,   7],
       [  7,  10,   9],
       [ 14,  11,  20],
       [ 22,   5,  11]])

In [35]:
c[4:,:] = [3,4,5]
c

array([[505,  65,   4],
       [  4,   7,   6],
       [ 11,   8,  17],
       [ 19,   2,   8]])

In [36]:
# insert row
np.append(c, [[1,1,1]], axis=0)

array([[505,  65,   4],
       [  4,   7,   6],
       [ 11,   8,  17],
       [ 19,   2,   8],
       [  1,   1,   1]])

In [45]:
# column insert
np.append(c, [[1],[1],[0],[1]], axis=1)

array([[505,  65,   4,   1],
       [  4,   7,   6,   1],
       [ 11,   8,  17,   0],
       [ 19,   2,   8,   1]])

In [48]:
# column delete
np.delete(c,(1,2),axis=1) 

array([[505],
       [  4],
       [ 11],
       [ 19]])