In [1]:
import numpy as np


In [3]:
np.loadtxt('data.txt',dtype='str')

FileNotFoundError: data.txt not found.

In [ ]:
np.loadtxt('data1.txt',delimiter=',') ##delimiter no ko space dega,todega

array([[45., 65., 78., 98.],
       [23., 19.,  3., 88.],
       [ 1.,  4.,  5.,  6.]])

In [ ]:
a=np.random.randint(1,100,[3,5])
a

array([[31, 12, 77, 69, 71],
       [77, 12, 41, 36, 91],
       [17, 82, 37, 41,  8]])

In [ ]:
sum(a) ##ek level tk sum karta h

array([122, 169, 175,  81, 167])

numpy has given this for doing this whole sum a.sum()


In [ ]:
a.sum(axis=1)

array([207, 274, 233])

In [ ]:
a.max(axis=1)

array([68, 97, 65])

In [ ]:
a

array([[29, 19, 30, 68, 61],
       [43, 85, 97,  2, 47],
       [50, 65, 48, 11, 59]])

argmax gives the max value in the array

In [ ]:
a.argmax()

7

In [ ]:
a.flatten()

array([29, 19, 30, 68, 61, 43, 85, 97,  2, 47, 50, 65, 48, 11, 59])